// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6W3_QArIdgD3nJyWFCRi4P25R4O-ZCHk',
    appId: '1:1093395860464:web:aa27b411ca6b6d66aa6b35',
    messagingSenderId: '1093395860464',
    projectId: 'todo-414b7',
    authDomain: 'todo-414b7.firebaseapp.com',
    storageBucket: 'todo-414b7.firebasestorage.app',
    measurementId: 'G-NDVDDS6Y6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5UdNGGdX7DxMKUGpcByGLHgCecStU75A',
    appId: '1:1093395860464:android:0f15b718b4acefb6aa6b35',
    messagingSenderId: '1093395860464',
    projectId: 'todo-414b7',
    storageBucket: 'todo-414b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTnaGh6ZMNzs4CsaG7tJypZkVLntYPF9I',
    appId: '1:1093395860464:ios:95e122914e017951aa6b35',
    messagingSenderId: '1093395860464',
    projectId: 'todo-414b7',
    storageBucket: 'todo-414b7.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTnaGh6ZMNzs4CsaG7tJypZkVLntYPF9I',
    appId: '1:1093395860464:ios:95e122914e017951aa6b35',
    messagingSenderId: '1093395860464',
    projectId: 'todo-414b7',
    storageBucket: 'todo-414b7.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6W3_QArIdgD3nJyWFCRi4P25R4O-ZCHk',
    appId: '1:1093395860464:web:7f767aee845833dfaa6b35',
    messagingSenderId: '1093395860464',
    projectId: 'todo-414b7',
    authDomain: 'todo-414b7.firebaseapp.com',
    storageBucket: 'todo-414b7.firebasestorage.app',
    measurementId: 'G-KGGWNEPBWF',
  );
}
